service: user-service

frameworkVersion: '3'

package:
  patterns:
    - '!.**/**'

provider:
  name: aws
  runtime: python3.9
  region: eu-north-1
  iamManagedPolicies:
    - "arn:aws:iam::381492106198:policy/UserServiceReadSecrets"

functions:
   registration:
      handler: src.integration.user_controller.registration_handler
      events:
         - http:
            path: user/register
            method: post
            integration: lambda-proxy
            cors: true

    sign_in:
      handler: src.integration.user_controller.sign_in
        events:
          - http:
              path: user/sign_in
              method: post
              integration: lambda-proxy
              cors: true


plugins:
  - serverless-wsgi
  - serverless-python-requirements